"""USSD menu copy — English, Kiswahili, French, Portuguese."""

LANG_BY_CHOICE = {
    "1": "english",
    "2": "swahili",
    "3": "french",
    "4": "portuguese",
}

SUPPORTED_LANGS = tuple(LANG_BY_CHOICE.values())

USSD_STRINGS: dict[str, dict[str, str]] = {
    "english": {
        "welcome": "CON ChaguoAI\n1.Method Match\n2.Report Side Effects\n3.Check Method\n4.Contact CHW\n5.Change Language",
        "language": "CON ChaguoAI\n1.English\n2.Kiswahili\n3.Francais\n4.Portuguese",
        "side_effect_prompt": "CON Describe your side effect briefly:",
        "side_effect_saved": "END Side effect recorded. A health worker will review it.",
        "no_match": "END No Method Match found. Dial 1 to start Method Match.",
        "hotline": "END Call 0800-720-593 for clinical support.",
        "invalid": "END Invalid choice. Dial again.",
        "match_prefix": "END Match: ",
        "match_error": "END We saved your answers but could not analyze now. Try again later.",
        "queued": "END Answers saved. Your match is being prepared. Dial again and press 3 to view it in 1-2 min.",
        "still_processing": "END Your match is still being prepared. Press 3 again shortly.",
        "geo_country": "CON Analytics only: Enter your country (e.g. Kenya):",
        "geo_area": "CON Analytics only: Enter your county/region:",
        "geo_invalid": "END Invalid entry. Dial again and enter a valid country or region.",
        "q1": "CON Q1/15: How old are you? (number e.g. 25)",
        "q2": "CON Q2/13: Last period / pregnancy?\n1.Within 4 wks\n2.Unsure\n3.Pregnant",
        "q3": "CON Q3/13: Baby under 6 months?\n1.Yes\n2.No",
        "q3a": "CON Q3a: Breastfeeding only?\n1.Yes\n2.No",
        "q4": "CON Q4/13: Living children? (number e.g. 0)",
        "q5": "CON Q5/13: Want more children?\n1.Yes in 2 yrs\n2.Yes later\n3.No",
        "q6": "CON Q6/13: Health conditions? (e.g. 1,2 or 7)\n1.BP 2.Diabetes 3.Heart 4.Liver 5.Cancer 6.Migraine 7.None",
        "q7": "CON Q7/13: Living with HIV?\n1.Yes\n2.No\n3.Prefer not say",
        "q8": "CON Q8/13: Do you smoke?\n1.Yes\n2.No",
        "q9": "CON Q9/13: Used contraception before?\n1.Yes\n2.No",
        "q9a": "CON Q9a: Did you stop?\n1.Still using\n2.Side effects\n3.Other\n4.Switched",
        "q10": "CON Q10/13: Partner supports FP?\n1.Yes\n2.No\n3.No partner",
        "q11": "CON Q11/13: Facility access?\n1.Easy\n2.Sometimes hard\n3.Very hard",
        "q12": "CON Q12/13: STI protection concern?\n1.Yes\n2.No",
        "q13": "CON Q13/13: Methods to avoid? (e.g. 1,2 or 5)\n1.Pills 2.Injectables 3.IUD 4.Implants 5.None",
    },
    "swahili": {
        "welcome": "CON ChaguoAI\n1.Njia Inayonifaa\n2.Ripoti Madhara\n3.Angalia Njia\n4.Piga CHW\n5.Badilisha Lugha",
        "language": "CON ChaguoAI\n1.Kiingereza\n2.Kiswahili\n3.Kifaransa\n4.Kireno",
        "side_effect_prompt": "CON Eleza madhara yako kwa ufupi:",
        "side_effect_saved": "END Madhara yamehifadhiwa. Mhudumu ataangalia.",
        "no_match": "END Hakuna mapendekezo. Piga 1 kuanza Method Match.",
        "hotline": "END Piga 0800-720-593 kwa msaada.",
        "invalid": "END Chaguo si sahihi. Piga tena.",
        "match_prefix": "END Mapendekezo: ",
        "match_error": "END Tumehifadhi majibu yako lakini tuchambua baadaye.",
        "queued": "END Majibu yamehifadhiwa. Mapendekezo yanatayarishwa. Piga tena na chagua 3 baada ya dakika 1-2.",
        "still_processing": "END Mapendekezo bado yanatayarishwa. Jaribu 3 tena hivi karibuni.",
        "geo_country": "CON Kwa takwimu tu: Andika nchi yako (mf. Kenya):",
        "geo_area": "CON Kwa takwimu tu: Andika kaunti/eneo lako:",
        "geo_invalid": "END Ulichoandika si sahihi. Piga tena.",
        "q1": "CON Q1/15: Una umri gani? (nambari mf. 25)",
        "q2": "CON Q2/13: Hedhi / ujauzito?\n1.Ndani wiki 4\n2.Sina uhakika\n3.Nina mimba",
        "q3": "CON Q3/13: Mtoto chini miezi 6?\n1.Ndio\n2.Hapana",
        "q3a": "CON Q3a: Unanyonyesha pekee?\n1.Ndio\n2.Hapana",
        "q4": "CON Q4/13: Watoto wangapi? (nambari mf. 0)",
        "q5": "CON Q5/13: Unataka watoto zaidi?\n1.Ndio miaka 2\n2.Ndio baadaye\n3.Hapana",
        "q6": "CON Q6/13: Hali ya kiafya? (mf. 1,2 au 7)\n1.BP 2.Kisukari 3.Moyo 4.Ini 5.Saratani 6.Migraine 7.Hakuna",
        "q7": "CON Q7/13: Unaishi na HIV?\n1.Ndio\n2.Hapana\n3.Sipendelei",
        "q8": "CON Q8/13: Unavuta sigara?\n1.Ndio\n2.Hapana",
        "q9": "CON Q9/13: Umewahi kutumia uzazi?\n1.Ndio\n2.Hapana",
        "q9a": "CON Q9a: Uliacha?\n1.Bado\n2.Madhara\n3.Nyingine\n4.Nilibadilisha",
        "q10": "CON Q10/13: Mpenzi anaunga mkono?\n1.Ndio\n2.Hapana\n3.Sina mpenzi",
        "q11": "CON Q11/13: Kufika kituo cha afya?\n1.Rahisi\n2.Wakati mwingine\n3.Ngumu sana",
        "q12": "CON Q12/13: Wajali STI?\n1.Ndio\n2.Hapana",
        "q13": "CON Q13/13: Njia za kuepuka? (mf. 1,2 au 5)\n1.Pills 2.Injectables 3.IUD 4.Implants 5.Hakuna",
    },
    "french": {
        "welcome": "CON ChaguoAI\n1.Method Match\n2.Effets secondaires\n3.Voir methode\n4.Contacter CHW\n5.Changer langue",
        "language": "CON ChaguoAI\n1.Anglais\n2.Kiswahili\n3.Francais\n4.Portugais",
        "side_effect_prompt": "CON Decrivez brievement l'effet secondaire:",
        "side_effect_saved": "END Effet enregistre. Un agent de sante va examiner.",
        "no_match": "END Aucune recommandation. Tapez 1 pour Method Match.",
        "hotline": "END Appelez 0800-720-593 pour aide clinique.",
        "invalid": "END Choix invalide. Recomposez.",
        "match_prefix": "END Recommandation: ",
        "match_error": "END Reponses enregistrees. Analyse impossible maintenant.",
        "queued": "END Reponses enregistrees. Recommandation en cours. Recomposez et tapez 3 dans 1-2 min.",
        "still_processing": "END Recommandation en preparation. Reessayez option 3 bientot.",
        "geo_country": "CON Stats seulement: Entrez votre pays (ex. Kenya):",
        "geo_area": "CON Stats seulement: Entrez region/comte:",
        "geo_invalid": "END Entree invalide. Recomposez.",
        "q1": "CON Q1/15: Quel age avez-vous? (ex. 25)",
        "q2": "CON Q2/13: Regles / grossesse?\n1.<4 sem\n2.Incertain\n3.Enceinte",
        "q3": "CON Q3/13: Bebe <6 mois?\n1.Oui\n2.Non",
        "q3a": "CON Q3a: Allaitement exclusif?\n1.Oui\n2.Non",
        "q4": "CON Q4/13: Enfants vivants? (ex. 0)",
        "q5": "CON Q5/13: Plus d'enfants?\n1.Oui 2 ans\n2.Oui plus tard\n3.Non",
        "q6": "CON Q6/13: Sante? (ex. 1,2 ou 7)\n1.TA 2.Diabete 3.Coeur 4.Foie 5.Cancer 6.Migraine 7.Aucun",
        "q7": "CON Q7/13: VIH?\n1.Oui\n2.Non\n3.Prefere pas",
        "q8": "CON Q8/13: Fumez-vous?\n1.Oui\n2.Non",
        "q9": "CON Q9/13: Contraception avant?\n1.Oui\n2.Non",
        "q9a": "CON Q9a: Arretee?\n1.Encore\n2.Effets\n3.Autre\n4.Change",
        "q10": "CON Q10/13: Partenaire soutient PF?\n1.Oui\n2.Non\n3.Pas partenaire",
        "q11": "CON Q11/13: Acces centre sante?\n1.Facile\n2.Parfois\n3.Tres difficile",
        "q12": "CON Q12/13: Souci IST?\n1.Oui\n2.Non",
        "q13": "CON Q13/13: Methodes a eviter? (ex. 1,2 ou 5)\n1.Pilules 2.Injectables 3.Stérilet 4.Implants 5.Aucune",
    },
    "portuguese": {
        "welcome": "CON ChaguoAI\n1.Method Match\n2.Efeitos colaterais\n3.Ver metodo\n4.Contactar CHW\n5.Mudar idioma",
        "language": "CON ChaguoAI\n1.Ingles\n2.Kiswahili\n3.Frances\n4.Portugues",
        "side_effect_prompt": "CON Descreva brevemente o efeito colateral:",
        "side_effect_saved": "END Efeito registado. Um agente de saude vai rever.",
        "no_match": "END Sem recomendacao. Marque 1 para Method Match.",
        "hotline": "END Ligue 0800-720-593 para apoio clinico.",
        "invalid": "END Escolha invalida. Marque novamente.",
        "match_prefix": "END Recomendacao: ",
        "match_error": "END Respostas guardadas. Nao foi possivel analisar agora.",
        "queued": "END Respostas guardadas. Recomendacao a preparar. Marque 3 em 1-2 min.",
        "still_processing": "END Recomendacao em preparacao. Tente opcao 3 em breve.",
        "geo_country": "CON So estatisticas: Indique o pais (ex. Quenia):",
        "geo_area": "CON So estatisticas: Indique regiao/distrito:",
        "geo_invalid": "END Entrada invalida. Marque novamente.",
        "q1": "CON Q1/15: Qual a sua idade? (ex. 25)",
        "q2": "CON Q2/13: Menstruacao / gravidez?\n1.<4 sem\n2.Incerto\n3.Gravida",
        "q3": "CON Q3/13: Bebe <6 meses?\n1.Sim\n2.Nao",
        "q3a": "CON Q3a: Amamentacao exclusiva?\n1.Sim\n2.Nao",
        "q4": "CON Q4/13: Filhos vivos? (ex. 0)",
        "q5": "CON Q5/13: Mais filhos?\n1.Sim 2 anos\n2.Sim depois\n3.Nao",
        "q6": "CON Q6/13: Saude? (ex. 1,2 ou 7)\n1.PA 2.Diabetes 3.Coracao 4.Figado 5.Cancro 6.Enxaqueca 7.Nenhum",
        "q7": "CON Q7/13: HIV?\n1.Sim\n2.Nao\n3.Prefiro nao",
        "q8": "CON Q8/13: Fuma?\n1.Sim\n2.Nao",
        "q9": "CON Q9/13: Contracepcao antes?\n1.Sim\n2.Nao",
        "q9a": "CON Q9a: Parou?\n1.Ainda\n2.Efeitos\n3.Outro\n4.Mudou",
        "q10": "CON Q10/13: Parceiro apoia PF?\n1.Sim\n2.Nao\n3.Sem parceiro",
        "q11": "CON Q11/13: Acesso unidade saude?\n1.Facil\n2.As vezes\n3.Muito dificil",
        "q12": "CON Q12/13: Preocupacao IST?\n1.Sim\n2.Nao",
        "q13": "CON Q13/13: Metodos a evitar? (ex. 1,2 ou 5)\n1.Pilulas 2.Injectaveis 3.DIU 4.Implantes 5.Nenhum",
    },
}


def ussd_text(lang: str, key: str) -> str:
    bucket = USSD_STRINGS.get(lang) or USSD_STRINGS["english"]
    return bucket.get(key) or USSD_STRINGS["english"][key]
